### PR TITLE
Feature/user icon

### PR DESCRIPTION
**Pull request by chuanlin2018**
This branch added a user icon to the right of the top bar. When clicked, the detail user info will display.
Also, the wizard project under projects was removed because it's no longer compatible with latest version of lib and not worth to fix all the problems. 
Tested locally with dap tool and dmp tool.
Local projects (dmp, portal, etc.) need to add following lines in angular.json to be able to display the user icon unless they already using fontawesome:
"styles": [
		…
		              "../node_modules/oarng/src/assets/styles/font-awesome/css/font-awesome.min.css",
		…
]

### CODE REVIEW

**Comment by RayPlante** [comment]
@chuanlin2018 This PR is a bit challenging to review via GitHub because over 1700 were changed (See "Files changed" above).  This appears to be mainly due to the inclusion of the fontawesome library(s).
  * This repo includes both `fontawesome` and `fontawesome-free-5.15.4-web`.  Are both of these needed?  Are they different vesions of the same thing?
  * Given that we should never be changing the individual files in this library, is there a different way to include these in our project?
      * Can we these be bundled into a single file somehow?
      * Can our build system retrieve them from an external source?

**Comment by chuanlin2018** [comment]
Yes these are two different version of the same thing. Mostly overlapped. I wanted to use the newer version because there are some new icons but at the end I realized that some of the social media icons in the footer didn't show up for some reason. So I was unable to remove the old version. I'll try to keep just one version.

**Comment by chuanlin2018** [comment]
The new fontawesome lib was removed and tested.

**Review by RayPlante — APPROVED** [review]
Tested this as part of oar-dmp and it worked.

**Pull request merged**
